# Generated by Django 5.1.5 on 2025-02-21 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, verbose_name='История чата'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры анализа'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='result',
            field=models.JSONField(blank=True, default=dict, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('done', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
